### PR TITLE
Fix discription of subnet

### PR DESCRIPTION
**Pull request by yanheven**
different subnets are L3 invisible, not L2 invisible, because different
subnets in same network are L2 visible.

### CODE REVIEW

**Comment by yeasy** [comment]
Different subnets are not visible in L2, event in the same network.
That's why we say L3 can split broadcast domains.
Right?

**Comment by yanheven** [comment]
I have tested that 2 vms in different subnets in  the same network, can arping each other.

**Comment by yeasy** [comment]
Typically, arp is only meaningful in the same subnet. 
Can you give more details on your testing?

**Comment by yanheven** [comment]
"A subnet in Neutron is a layer 3 resource", so maybe it makes no sence to talk about  weather they layer 2 visible. as for layer 3, different subnets are really invisible.

**Comment by yeasy** [comment]
We may not need to emphasize this point here.
It actually is that neither l3 nor l2 is visible for different subnets.
However, let's get it merged first.

**Pull request merged**
